[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18.20.0"
  NPM_FLAGS = "--legacy-peer-deps"

# Handle form submissions and API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle form submissions for Netlify Forms
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Enable form detection
[dev]
  publish = "build"
  targetPort = 3000
  framework = "create-react-app"

# Form submission settings
[context.production.environment]
  NODE_VERSION = "18.x"
  NPM_VERSION = "9.x"
